modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"

[[mods]]
modId="capabilitytest1"
version="${file.jarVersion}"
displayName="Capability Test 1"
authors="Tictim"
description='''

'''

[[dependencies.paraglider]]
	modId="forge"
	mandatory=true
	versionRange="[32,)"
	ordering="NONE"
	side="BOTH"